---

- name: Create microk8s group
  group:
    name: microk8s
    state: present

- name: Add vagrant to microk8s user group
  user:
    name: vagrant
    group: microk8s
    append: yes

- name: Check microk8s status
  command: microk8s status --wait-ready

- name: Enable DNS module
  command: microk8s enable dns dashboard prometheus

- name: Create landing directory for kubernetes yaml
  file:
    path: /tmp/dev
    state: directory

- name: Copy kubernetes yaml to target machine
  copy:
    src: ../files/kubernetes.yml
    dest: /tmp/dev

- name: Apply kubernetes yaml (deployment and service)
  command: microk8s kubectl apply -f /tmp/dev/kubernetes.yml

- name: Forward prometheus and grafana ports
  command: kubectl proxy &
  command: microk8s kubectl port-forward -n monitoring service/prometheus-k8s --address 0.0.0.0 9090:9090 &
  command: microk8s kubectl port-forward -n monitoring service/grafana --address 0.0.0.0 3000:3000 &