- name: Intsall metricbeat and configure microk8s
  hosts: workers
  remote_user: vagrant
  become: yes
  become_user: root
  
  roles:
  - microk8s
  # - metricbeat # Killed because metricbeat setup with kubernetes is not possibel due to time constraints